export const HomeExample = [
  {
    id: 1,
    cost: 3000,
    name: "Just In",
    img: "/logo192.png",
  },
  {
    id: 2,
    cost: 1500,
    name: "Book 1",
    img: "/favicon.ico",
  },
  {
    id: 3,
    cost: 5000,
    name: "Robert Kiosaki",
    img: "/logo512.png",
  },
  {
    id: 4,
    cost: 3000,
    name: "Just In",
    img: "/logo192.png",
  },
  {
    id: 5,
    cost: 1500,
    name: "Book 1",
    img: "/favicon.ico",
  },
  {
    id: 6,
    cost: 5000,
    name: "Robert Kiosaki",
    img: "/logo512.png",
  },
  {
    id: 7,
    cost: 3000,
    name: "Just In",
    img: "/logo192.png",
  },
  {
    id: 8,
    cost: 1500,
    name: "Book 1",
    img: "/favicon.ico",
  },
  {
    id: 9,
    cost: 5000,
    name: "Robert Kiosaki",
    img: "/logo512.png",
  },
  {
    id: 10,
    cost: 3000,
    name: "Just In",
    img: "/logo192.png",
  },
  {
    id: 11,
    cost: 1500,
    name: "Book 1",
    img: "/favicon.ico",
  },
  {
    id: 12,
    cost: 5000,
    name: "Robert Kiosaki",
    img: "/logo512.png",
  },
  {
    id: 13,
    cost: 3000,
    name: "Just In",
    img: "/logo192.png",
  },
  {
    id: 14,
    cost: 1500,
    name: "Book 1",
    img: "/favicon.ico",
  },
  {
    id: 15,
    cost: 5000,
    name: "Robert Kiosaki",
    img: "/logo512.png",
  },
  {
    id: 16,
    cost: 3000,
    name: "Just In",
    img: "/logo192.png",
  },
  {
    id: 17,
    cost: 1500,
    name: "Book 1",
    img: "/favicon.ico",
  },
  {
    id: 18,
    cost: 5000,
    name: "Robert Kiosaki",
    img: "/logo512.png",
  },
  {
    id: 19,
    cost: 3000,
    name: "Just In",
    img: "/logo192.png",
  },
  {
    id: 20,
    cost: 1500,
    name: "Book 1",
    img: "/favicon.ico",
  },
  {
    id: 21,
    cost: 5000,
    name: "Robert Kiosaki",
    img: "/logo512.png",
  },
];
